#############################################################################
# Makefile for building: CMDSim
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? 7? 11 17:21:28 2013
# Project:  CMDSim.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.4/bin/qmake -o Makefile CMDSim.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.4/include/QtCore -I/usr/local/Trolltech/Qt-4.8.4/include/QtGui -I/usr/local/Trolltech/Qt-4.8.4/include -Iqwtinc -I/usr/local/qwt-6.1.0-rc3/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.4/lib -L/home/mars/cmd_sim/../../../usr/local/qwt-6.1.0-rc3/lib/ -lqwt -lQtGui -L/usr/local/Trolltech/Qt-4.8.4/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cmdsimmw.cpp \
		rfm2gse.cpp \
		commonch.cpp \
		c75c3dllencap.cpp \
		lvdtch.cpp \
		commbrd.cpp \
		apdapter.cpp \
		setbrddlg.cpp \
		setwpdlg.cpp \
		brd75c3.cpp \
		setlbrdparadlg.cpp \
		siggen.cpp \
		sigpara.cpp \
		cmdsimmw_init.cpp \
		oscilloscope/curvedata.cpp \
		oscilloscope/knob.cpp \
		oscilloscope/plot.cpp \
		oscilloscope/samplingthread.cpp \
		oscilloscope/signaldata.cpp \
		oscilloscope/wheelbox.cpp \
		oscilloscope/qwtoscmain.cpp moc_cmdsimmw.cpp \
		moc_rfm2gse.cpp \
		moc_commonch.cpp \
		moc_lvdtch.cpp \
		moc_commbrd.cpp \
		moc_apdapter.cpp \
		moc_setbrddlg.cpp \
		moc_setwpdlg.cpp \
		moc_brd75c3.cpp \
		moc_setlbrdparadlg.cpp \
		moc_siggen.cpp \
		moc_sigpara.cpp \
		moc_knob.cpp \
		moc_plot.cpp \
		moc_samplingthread.cpp \
		moc_wheelbox.cpp \
		moc_qwtoscmain.cpp \
		qrc_qres.cpp
OBJECTS       = main.o \
		cmdsimmw.o \
		rfm2gse.o \
		commonch.o \
		c75c3dllencap.o \
		lvdtch.o \
		commbrd.o \
		apdapter.o \
		setbrddlg.o \
		setwpdlg.o \
		brd75c3.o \
		setlbrdparadlg.o \
		siggen.o \
		sigpara.o \
		cmdsimmw_init.o \
		curvedata.o \
		knob.o \
		plot.o \
		samplingthread.o \
		signaldata.o \
		wheelbox.o \
		qwtoscmain.o \
		moc_cmdsimmw.o \
		moc_rfm2gse.o \
		moc_commonch.o \
		moc_lvdtch.o \
		moc_commbrd.o \
		moc_apdapter.o \
		moc_setbrddlg.o \
		moc_setwpdlg.o \
		moc_brd75c3.o \
		moc_setlbrdparadlg.o \
		moc_siggen.o \
		moc_sigpara.o \
		moc_knob.o \
		moc_plot.o \
		moc_samplingthread.o \
		moc_wheelbox.o \
		moc_qwtoscmain.o \
		qrc_qres.o
DIST          = /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		CMDSim.pro
QMAKE_TARGET  = CMDSim
DESTDIR       = 
TARGET        = CMDSim

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_cmdsimmw.h ui_setbrddlg.h ui_setwpdlg.h ui_setlbrdparadlg.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CMDSim.pro  /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl
	$(QMAKE) -o Makefile CMDSim.pro
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile CMDSim.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CMDSim1.0.0 || $(MKDIR) .tmp/CMDSim1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CMDSim1.0.0/ && $(COPY_FILE) --parents cmdsimmw.h rfm2gse.h cmddefs.h C75C3Expls.h c75c3funcp.h commonch.h c75c3dllencap.h lvdtch.h commbrd.h apdapter.h setbrddlg.h setwpdlg.h brd75c3.h setlbrdparadlg.h siggen.h sigpara.h oscilloscope/curvedata.h oscilloscope/knob.h oscilloscope/plot.h oscilloscope/samplingthread.h oscilloscope/signaldata.h oscilloscope/wheelbox.h oscilloscope/qwtoscmain.h .tmp/CMDSim1.0.0/ && $(COPY_FILE) --parents qres.qrc .tmp/CMDSim1.0.0/ && $(COPY_FILE) --parents main.cpp cmdsimmw.cpp rfm2gse.cpp commonch.cpp c75c3dllencap.cpp lvdtch.cpp commbrd.cpp apdapter.cpp setbrddlg.cpp setwpdlg.cpp brd75c3.cpp setlbrdparadlg.cpp siggen.cpp sigpara.cpp cmdsimmw_init.cpp oscilloscope/curvedata.cpp oscilloscope/knob.cpp oscilloscope/plot.cpp oscilloscope/samplingthread.cpp oscilloscope/signaldata.cpp oscilloscope/wheelbox.cpp oscilloscope/qwtoscmain.cpp .tmp/CMDSim1.0.0/ && $(COPY_FILE) --parents cmdsimmw.ui setbrddlg.ui setwpdlg.ui setlbrdparadlg.ui .tmp/CMDSim1.0.0/ && (cd `dirname .tmp/CMDSim1.0.0` && $(TAR) CMDSim1.0.0.tar CMDSim1.0.0 && $(COMPRESS) CMDSim1.0.0.tar) && $(MOVE) `dirname .tmp/CMDSim1.0.0`/CMDSim1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CMDSim1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cmdsimmw.cpp moc_rfm2gse.cpp moc_commonch.cpp moc_lvdtch.cpp moc_commbrd.cpp moc_apdapter.cpp moc_setbrddlg.cpp moc_setwpdlg.cpp moc_brd75c3.cpp moc_setlbrdparadlg.cpp moc_siggen.cpp moc_sigpara.cpp moc_knob.cpp moc_plot.cpp moc_samplingthread.cpp moc_wheelbox.cpp moc_qwtoscmain.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cmdsimmw.cpp moc_rfm2gse.cpp moc_commonch.cpp moc_lvdtch.cpp moc_commbrd.cpp moc_apdapter.cpp moc_setbrddlg.cpp moc_setwpdlg.cpp moc_brd75c3.cpp moc_setlbrdparadlg.cpp moc_siggen.cpp moc_sigpara.cpp moc_knob.cpp moc_plot.cpp moc_samplingthread.cpp moc_wheelbox.cpp moc_qwtoscmain.cpp
moc_cmdsimmw.cpp: oscilloscope/qwtoscmain.h \
		oscilloscope/samplingthread.h \
		qwtinc/qwt_sampling_thread.h \
		qwtinc/qwt_global.h \
		cmdsimmw.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) cmdsimmw.h -o moc_cmdsimmw.cpp

moc_rfm2gse.cpp: rfminc/rfm2g_windows.h \
		rfminc/rfm2g_types.h \
		rfminc/rfm2gdll_stdc.h \
		rfminc/rfm2g_api.h \
		rfminc/rfm2g_osspec.h \
		rfminc/rfm2g_defs.h \
		rfminc/rfm2g_errno.h \
		rfminc/rfm2g_regs.h \
		rfminc/pmc5565_nt.h \
		cmddefs.h \
		rfm2gse.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) rfm2gse.h -o moc_rfm2gse.cpp

moc_commonch.cpp: c75c3funcp.h \
		C75C3Expls.h \
		commonch.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) commonch.h -o moc_commonch.cpp

moc_lvdtch.cpp: c75c3dllencap.h \
		C75C3Expls.h \
		c75c3funcp.h \
		commonch.h \
		lvdtch.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) lvdtch.h -o moc_lvdtch.cpp

moc_commbrd.cpp: commbrd.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) commbrd.h -o moc_commbrd.cpp

moc_apdapter.cpp: apdapter.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) apdapter.h -o moc_apdapter.cpp

moc_setbrddlg.cpp: setbrddlg.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) setbrddlg.h -o moc_setbrddlg.cpp

moc_setwpdlg.cpp: qwtinc/qwt_dial.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h \
		qwtinc/qwt_abstract_scale_draw.h \
		qwtinc/qwt_scale_div.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_dial_needle.h \
		setwpdlg.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) setwpdlg.h -o moc_setwpdlg.cpp

moc_brd75c3.cpp: commbrd.h \
		c75c3dllencap.h \
		C75C3Expls.h \
		c75c3funcp.h \
		brd75c3.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) brd75c3.h -o moc_brd75c3.cpp

moc_setlbrdparadlg.cpp: setlbrdparadlg.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) setlbrdparadlg.h -o moc_setlbrdparadlg.cpp

moc_siggen.cpp: cmddefs.h \
		sigpara.h \
		siggen.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) siggen.h -o moc_siggen.cpp

moc_sigpara.cpp: cmddefs.h \
		sigpara.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) sigpara.h -o moc_sigpara.cpp

moc_knob.cpp: oscilloscope/knob.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) oscilloscope/knob.h -o moc_knob.cpp

moc_plot.cpp: qwtinc/qwt_plot.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_plot_dict.h \
		qwtinc/qwt_plot_item.h \
		qwtinc/qwt_legend_data.h \
		qwtinc/qwt_graphic.h \
		qwtinc/qwt_null_paintdevice.h \
		qwtinc/qwt_scale_map.h \
		qwtinc/qwt_transform.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_system_clock.h \
		oscilloscope/plot.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) oscilloscope/plot.h -o moc_plot.cpp

moc_samplingthread.cpp: qwtinc/qwt_sampling_thread.h \
		qwtinc/qwt_global.h \
		oscilloscope/samplingthread.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) oscilloscope/samplingthread.h -o moc_samplingthread.cpp

moc_wheelbox.cpp: oscilloscope/wheelbox.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) oscilloscope/wheelbox.h -o moc_wheelbox.cpp

moc_qwtoscmain.cpp: oscilloscope/samplingthread.h \
		qwtinc/qwt_sampling_thread.h \
		qwtinc/qwt_global.h \
		oscilloscope/qwtoscmain.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) oscilloscope/qwtoscmain.h -o moc_qwtoscmain.cpp

compiler_rcc_make_all: qrc_qres.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qres.cpp
qrc_qres.cpp: qres.qrc \
		image/edu_mathematics.ico \
		image/package_development.ico \
		image/hwinfo.ico \
		image/package_settings.ico \
		image/terminal.ico \
		image/kcmprocessor.ico \
		image/kcmmemory.ico \
		image/password.ico \
		image/taskbar.ico \
		image/kmenuedit.ico \
		image/konsole.ico \
		image/MW.ico \
		image/linuxconf.ico
	/usr/local/Trolltech/Qt-4.8.4/bin/rcc -name qres qres.qrc -o qrc_qres.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cmdsimmw.h ui_setbrddlg.h ui_setwpdlg.h ui_setlbrdparadlg.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cmdsimmw.h ui_setbrddlg.h ui_setwpdlg.h ui_setlbrdparadlg.h
ui_cmdsimmw.h: cmdsimmw.ui \
		qwtinc/qwt_plot.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_plot_dict.h \
		qwtinc/qwt_plot_item.h \
		qwtinc/qwt_legend_data.h \
		qwtinc/qwt_graphic.h \
		qwtinc/qwt_null_paintdevice.h \
		qwtinc/qwt_scale_map.h \
		qwtinc/qwt_transform.h \
		qwtinc/qwt_interval.h
	/usr/local/Trolltech/Qt-4.8.4/bin/uic cmdsimmw.ui -o ui_cmdsimmw.h

ui_setbrddlg.h: setbrddlg.ui \
		qwtinc/qwt_knob.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h
	/usr/local/Trolltech/Qt-4.8.4/bin/uic setbrddlg.ui -o ui_setbrddlg.h

ui_setwpdlg.h: setwpdlg.ui \
		qwtinc/qwt_plot.h \
		qwtinc/qwt_dial.h \
		qwtinc/qwt_knob.h \
		qwtinc/qwt_text_label.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_plot_dict.h \
		qwtinc/qwt_plot_item.h \
		qwtinc/qwt_legend_data.h \
		qwtinc/qwt_graphic.h \
		qwtinc/qwt_null_paintdevice.h \
		qwtinc/qwt_scale_map.h \
		qwtinc/qwt_transform.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h \
		qwtinc/qwt_abstract_scale_draw.h \
		qwtinc/qwt_scale_div.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_text.h
	/usr/local/Trolltech/Qt-4.8.4/bin/uic setwpdlg.ui -o ui_setwpdlg.h

ui_setlbrdparadlg.h: setlbrdparadlg.ui \
		qwtinc/qwt_knob.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h
	/usr/local/Trolltech/Qt-4.8.4/bin/uic setlbrdparadlg.ui -o ui_setlbrdparadlg.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp cmdsimmw.h \
		oscilloscope/qwtoscmain.h \
		oscilloscope/samplingthread.h \
		qwtinc/qwt_sampling_thread.h \
		qwtinc/qwt_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cmdsimmw.o: cmdsimmw.cpp cmdsimmw.h \
		oscilloscope/qwtoscmain.h \
		oscilloscope/samplingthread.h \
		qwtinc/qwt_sampling_thread.h \
		qwtinc/qwt_global.h \
		ui_cmdsimmw.h \
		qwtinc/qwt_plot.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_plot_dict.h \
		qwtinc/qwt_plot_item.h \
		qwtinc/qwt_legend_data.h \
		qwtinc/qwt_graphic.h \
		qwtinc/qwt_null_paintdevice.h \
		qwtinc/qwt_scale_map.h \
		qwtinc/qwt_transform.h \
		qwtinc/qwt_interval.h \
		rfm2gse.h \
		rfminc/rfm2g_windows.h \
		rfminc/rfm2g_types.h \
		rfminc/rfm2gdll_stdc.h \
		rfminc/rfm2g_api.h \
		rfminc/rfm2g_osspec.h \
		rfminc/rfm2g_defs.h \
		rfminc/rfm2g_errno.h \
		rfminc/rfm2g_regs.h \
		rfminc/pmc5565_nt.h \
		cmddefs.h \
		C75C3Expls.h \
		c75c3dllencap.h \
		c75c3funcp.h \
		lvdtch.h \
		commonch.h \
		setbrddlg.h \
		setwpdlg.h \
		qwtinc/qwt_dial.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h \
		qwtinc/qwt_abstract_scale_draw.h \
		qwtinc/qwt_scale_div.h \
		qwtinc/qwt_dial_needle.h \
		sigpara.h \
		siggen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmdsimmw.o cmdsimmw.cpp

rfm2gse.o: rfm2gse.cpp rfm2gse.h \
		rfminc/rfm2g_windows.h \
		rfminc/rfm2g_types.h \
		rfminc/rfm2gdll_stdc.h \
		rfminc/rfm2g_api.h \
		rfminc/rfm2g_osspec.h \
		rfminc/rfm2g_defs.h \
		rfminc/rfm2g_errno.h \
		rfminc/rfm2g_regs.h \
		rfminc/pmc5565_nt.h \
		cmddefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rfm2gse.o rfm2gse.cpp

commonch.o: commonch.cpp commonch.h \
		c75c3funcp.h \
		C75C3Expls.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commonch.o commonch.cpp

c75c3dllencap.o: c75c3dllencap.cpp c75c3dllencap.h \
		C75C3Expls.h \
		c75c3funcp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o c75c3dllencap.o c75c3dllencap.cpp

lvdtch.o: lvdtch.cpp lvdtch.h \
		c75c3dllencap.h \
		C75C3Expls.h \
		c75c3funcp.h \
		commonch.h \
		cmddefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lvdtch.o lvdtch.cpp

commbrd.o: commbrd.cpp commbrd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commbrd.o commbrd.cpp

apdapter.o: apdapter.cpp apdapter.h \
		cmddefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o apdapter.o apdapter.cpp

setbrddlg.o: setbrddlg.cpp setbrddlg.h \
		ui_setbrddlg.h \
		qwtinc/qwt_knob.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setbrddlg.o setbrddlg.cpp

setwpdlg.o: setwpdlg.cpp setwpdlg.h \
		qwtinc/qwt_dial.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h \
		qwtinc/qwt_abstract_scale_draw.h \
		qwtinc/qwt_scale_div.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_dial_needle.h \
		ui_setwpdlg.h \
		qwtinc/qwt_knob.h \
		qwtinc/qwt_plot.h \
		qwtinc/qwt_plot_dict.h \
		qwtinc/qwt_plot_item.h \
		qwtinc/qwt_legend_data.h \
		qwtinc/qwt_graphic.h \
		qwtinc/qwt_null_paintdevice.h \
		qwtinc/qwt_scale_map.h \
		qwtinc/qwt_transform.h \
		qwtinc/qwt_text_label.h \
		qwtinc/qwt_plot_curve.h \
		qwtinc/qwt_plot_seriesitem.h \
		qwtinc/qwt_series_data.h \
		qwtinc/qwt_samples.h \
		qwtinc/qwt_point_3d.h \
		qwtinc/qwt_point_polar.h \
		qwtinc/qwt_math.h \
		qwtinc/qwt_series_store.h \
		qwtinc/qwt_point_data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setwpdlg.o setwpdlg.cpp

brd75c3.o: brd75c3.cpp brd75c3.h \
		commbrd.h \
		c75c3dllencap.h \
		C75C3Expls.h \
		c75c3funcp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brd75c3.o brd75c3.cpp

setlbrdparadlg.o: setlbrdparadlg.cpp setlbrdparadlg.h \
		ui_setlbrdparadlg.h \
		qwtinc/qwt_knob.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o setlbrdparadlg.o setlbrdparadlg.cpp

siggen.o: siggen.cpp siggen.h \
		cmddefs.h \
		sigpara.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o siggen.o siggen.cpp

sigpara.o: sigpara.cpp sigpara.h \
		cmddefs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sigpara.o sigpara.cpp

cmdsimmw_init.o: cmdsimmw_init.cpp cmdsimmw.h \
		oscilloscope/qwtoscmain.h \
		oscilloscope/samplingthread.h \
		qwtinc/qwt_sampling_thread.h \
		qwtinc/qwt_global.h \
		ui_cmdsimmw.h \
		qwtinc/qwt_plot.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_plot_dict.h \
		qwtinc/qwt_plot_item.h \
		qwtinc/qwt_legend_data.h \
		qwtinc/qwt_graphic.h \
		qwtinc/qwt_null_paintdevice.h \
		qwtinc/qwt_scale_map.h \
		qwtinc/qwt_transform.h \
		qwtinc/qwt_interval.h \
		rfm2gse.h \
		rfminc/rfm2g_windows.h \
		rfminc/rfm2g_types.h \
		rfminc/rfm2gdll_stdc.h \
		rfminc/rfm2g_api.h \
		rfminc/rfm2g_osspec.h \
		rfminc/rfm2g_defs.h \
		rfminc/rfm2g_errno.h \
		rfminc/rfm2g_regs.h \
		rfminc/pmc5565_nt.h \
		cmddefs.h \
		C75C3Expls.h \
		c75c3dllencap.h \
		c75c3funcp.h \
		lvdtch.h \
		commonch.h \
		setbrddlg.h \
		setwpdlg.h \
		qwtinc/qwt_dial.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h \
		qwtinc/qwt_abstract_scale_draw.h \
		qwtinc/qwt_scale_div.h \
		qwtinc/qwt_dial_needle.h \
		sigpara.h \
		siggen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmdsimmw_init.o cmdsimmw_init.cpp

curvedata.o: oscilloscope/curvedata.cpp oscilloscope/curvedata.h \
		qwtinc/qwt_series_data.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_samples.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_point_3d.h \
		qwtinc/qwt_point_polar.h \
		qwtinc/qwt_math.h \
		oscilloscope/signaldata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curvedata.o oscilloscope/curvedata.cpp

knob.o: oscilloscope/knob.cpp oscilloscope/knob.h \
		qwtinc/qwt_math.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_knob.h \
		qwtinc/qwt_abstract_slider.h \
		qwtinc/qwt_abstract_scale.h \
		qwtinc/qwt_round_scale_draw.h \
		qwtinc/qwt_abstract_scale_draw.h \
		qwtinc/qwt_scale_div.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_scale_engine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o knob.o oscilloscope/knob.cpp

plot.o: oscilloscope/plot.cpp oscilloscope/plot.h \
		qwtinc/qwt_plot.h \
		qwtinc/qwt_global.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_plot_dict.h \
		qwtinc/qwt_plot_item.h \
		qwtinc/qwt_legend_data.h \
		qwtinc/qwt_graphic.h \
		qwtinc/qwt_null_paintdevice.h \
		qwtinc/qwt_scale_map.h \
		qwtinc/qwt_transform.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_system_clock.h \
		oscilloscope/curvedata.h \
		qwtinc/qwt_series_data.h \
		qwtinc/qwt_samples.h \
		qwtinc/qwt_point_3d.h \
		qwtinc/qwt_point_polar.h \
		qwtinc/qwt_math.h \
		oscilloscope/signaldata.h \
		qwtinc/qwt_plot_grid.h \
		qwtinc/qwt_scale_div.h \
		qwtinc/qwt_plot_layout.h \
		qwtinc/qwt_plot_canvas.h \
		qwtinc/qwt_plot_marker.h \
		qwtinc/qwt_plot_curve.h \
		qwtinc/qwt_plot_seriesitem.h \
		qwtinc/qwt_series_store.h \
		qwtinc/qwt_plot_directpainter.h \
		qwtinc/qwt_curve_fitter.h \
		qwtinc/qwt_painter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plot.o oscilloscope/plot.cpp

samplingthread.o: oscilloscope/samplingthread.cpp oscilloscope/samplingthread.h \
		qwtinc/qwt_sampling_thread.h \
		qwtinc/qwt_global.h \
		oscilloscope/signaldata.h \
		qwtinc/qwt_math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o samplingthread.o oscilloscope/samplingthread.cpp

signaldata.o: oscilloscope/signaldata.cpp oscilloscope/signaldata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o signaldata.o oscilloscope/signaldata.cpp

wheelbox.o: oscilloscope/wheelbox.cpp oscilloscope/wheelbox.h \
		qwtinc/qwt_wheel.h \
		qwtinc/qwt_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wheelbox.o oscilloscope/wheelbox.cpp

qwtoscmain.o: oscilloscope/qwtoscmain.cpp oscilloscope/qwtoscmain.h \
		oscilloscope/samplingthread.h \
		qwtinc/qwt_sampling_thread.h \
		qwtinc/qwt_global.h \
		oscilloscope/plot.h \
		qwtinc/qwt_plot.h \
		qwtinc/qwt_text.h \
		qwtinc/qwt_plot_dict.h \
		qwtinc/qwt_plot_item.h \
		qwtinc/qwt_legend_data.h \
		qwtinc/qwt_graphic.h \
		qwtinc/qwt_null_paintdevice.h \
		qwtinc/qwt_scale_map.h \
		qwtinc/qwt_transform.h \
		qwtinc/qwt_interval.h \
		qwtinc/qwt_system_clock.h \
		oscilloscope/knob.h \
		oscilloscope/wheelbox.h \
		qwtinc/qwt_scale_engine.h \
		qwtinc/qwt_scale_div.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qwtoscmain.o oscilloscope/qwtoscmain.cpp

moc_cmdsimmw.o: moc_cmdsimmw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmdsimmw.o moc_cmdsimmw.cpp

moc_rfm2gse.o: moc_rfm2gse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rfm2gse.o moc_rfm2gse.cpp

moc_commonch.o: moc_commonch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commonch.o moc_commonch.cpp

moc_lvdtch.o: moc_lvdtch.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lvdtch.o moc_lvdtch.cpp

moc_commbrd.o: moc_commbrd.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_commbrd.o moc_commbrd.cpp

moc_apdapter.o: moc_apdapter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_apdapter.o moc_apdapter.cpp

moc_setbrddlg.o: moc_setbrddlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setbrddlg.o moc_setbrddlg.cpp

moc_setwpdlg.o: moc_setwpdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setwpdlg.o moc_setwpdlg.cpp

moc_brd75c3.o: moc_brd75c3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_brd75c3.o moc_brd75c3.cpp

moc_setlbrdparadlg.o: moc_setlbrdparadlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_setlbrdparadlg.o moc_setlbrdparadlg.cpp

moc_siggen.o: moc_siggen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_siggen.o moc_siggen.cpp

moc_sigpara.o: moc_sigpara.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sigpara.o moc_sigpara.cpp

moc_knob.o: moc_knob.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_knob.o moc_knob.cpp

moc_plot.o: moc_plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plot.o moc_plot.cpp

moc_samplingthread.o: moc_samplingthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_samplingthread.o moc_samplingthread.cpp

moc_wheelbox.o: moc_wheelbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wheelbox.o moc_wheelbox.cpp

moc_qwtoscmain.o: moc_qwtoscmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qwtoscmain.o moc_qwtoscmain.cpp

qrc_qres.o: qrc_qres.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qres.o qrc_qres.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

